{
  "openapi" : "3.0.2",
  "info" : {
    "title" : "Petstore Cart",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "/"
  } ],
  "paths" : {
    "/cart/new" : {
      "post" : {
        "summary" : "Add a Cart",
        "operationId" : "createCart",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Cart"
                },
                "examples" : {
                  "manu_cart" : {
                    "value" : {
                      "id" : 123,
                      "owner" : "Manu",
                      "status" : "Pending",
                      "items" : [ ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/cart/{id}/addItem" : {
      "post" : {
        "summary" : "Add an item to the cart",
        "operationId" : "addItem",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "Cart Id",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          },
          "examples" : {
            "manu_cart" : {
              "value" : "123"
            }
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "integer"
              },
              "examples" : {
                "manu_cart" : {
                  "value" : "1"
                }
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Cart"
                },
                "examples" : {
                  "manu_cart" : {
                    "value" : {
                      "id" : 123,
                      "owner" : "Manu",
                      "status" : "Pending",
                      "items" : [ 1 ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/cart/{id}/checkout" : {
      "post" : {
        "summary" : "Checkout the cart",
        "operationId" : "checkout",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "Cart Id",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          },
          "examples" : {
            "manu_cart" : {
              "value" : "123"
            }
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Cart"
                },
                "examples" : {
                  "manu_cart" : {
                    "value" : {
                      "id" : 123,
                      "owner" : "Manu",
                      "status" : "closed",
                      "items" : [ 1 ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Cart" : {
        "title" : "Root Type for Cart",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int32"
          },
          "owner" : {
            "type" : "string"
          },
          "status" : {
            "type" : "string"
          },
          "items" : {
            "type" : "array",
            "items" : {
              "type" : "integer",
              "format" : "int32"
            }
          }
        },
        "description" : "",
        "example" : {
          "id" : 1,
          "owner" : "Manu",
          "status" : "pending",
          "items" : [ 1 ]
        }
      }
    }
  }
}